microsoftgraph/msgraph-sdk-dotnet

docs/overview.md
The documentation was different from the way the SDK behaved.  Updated to reflect the way the SDK works.
=> updated query options documentation

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph/Microsoft.Graph.csproj
Nuget by default adds dependencies with specific version set to true. Don't do that so people can upgrade their nuget packages if they want.
=> Set SpecificVersion to false for nuget dependency

src/Microsoft.Graph/Requests/Generated/DriveItemContentRequestBuilder.cs, src/Microsoft.Graph/Requests/Generated/IDriveItemContentRequestBuilder.cs, src/Microsoft.Graph/Requests/Generated/IProfilePhotoContentRequestBuilder.cs, src/Microsoft.Graph/Requests/Generated/IThumbnailContentRequestBuilder.cs, src/Microsoft.Graph/Requests/Generated/ProfilePhotoContentRequestBuilder.cs, src/Microsoft.Graph/Requests/Generated/ThumbnailContentRequestBuilder.cs
This is needed in order to add things like the nameConflictBehavior query param when building the request. Also, would allow adding custom headers, etc.
Generated from [this PR](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/34).
=> Allow passing options collection to Request method for stream requests

src/Microsoft.Graph/Microsoft.Graph.nuspec, src/Microsoft.Graph/Properties/AssemblyInfo.cs, src/Microsoft.Graph/Requests/UploadChunkRequest.cs, tests/Microsoft.Graph.Test/Requests/Functional/OneDriveTests.cs
The auth context is set when the session is created. OneDrive for Business ignores the access token, OneDrive for Consumer returns an error if it is sent.
=> Remove auth header from uploadchunkrequest.cs

docs/overview.md, tests/Microsoft.Graph.Test/Microsoft.Graph.Test.csproj, tests/Microsoft.Graph.Test/Requests/Functional/OneNoteTests.cs, tests/Microsoft.Graph.Test/Requests/Functional/SchemaExtensionTests.cs, tests/Microsoft.Graph.Test/Requests/Functional/SharePointTests.cs
Forked off of OneNote work so only review commit 2b377e4. While I've seen the test run fine, we are blocked on running the tests again with this app registration since I can't delete the existing schema extensions and we've hit the max for number of schema extensions per app. The state machine appears broken so I can't get an extension to a deletable state.
=> Schema extensions

src/Microsoft.Graph.Core/Serialization/Serializer.cs
Fix for issue #180 
Json.Net (when it's parsing things as part of a JsonReader) sees strings that look like dates, and converts them to Date JTokens. This is problematic when the value of a string _is_ a date, but the field on the object is a string. It causes Dates to be converted to dates, then converted back to strings (using the CurrentLocale ).
This suppresses that default behavior.
=> Suppress JSON.Net's instinct to parse dates as dates

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, src/Microsoft.Graph.Core/Requests/IHttpProvider.cs, tests/Microsoft.Graph.Test/Requests/Functional/MiscTests.cs
This will enable users to set the timeout like this:
```
// Change the timeout interval from 100 sec (default) to 200 sec.
graphClient.HttpProvider.OverallTimeout = new TimeSpan(0,3,20);
```
=> Exposed timeout via ihttpprovider interface

src/Microsoft.Graph.Core/Serialization/DurationConverter.cs, tests/Microsoft.Graph.Core.Test/Serialization/DurationConverterTests.cs
It looks like there was a bug in both the serializer and the test.
The serializer should deserialize the value to a string and then use the `Duration(string)` signature to create a Duration object.
The serializer test should not use a JSON key-value pair because a duration is only a value. I also used the same serializer logic in `SerializerTests.cs` because it was a bit cleaner.
=> Fix Duration serializer and serializer test

README.md, docs/headers.md, docs/readme.md, src/Microsoft.Graph.Core/Requests/BaseRequest.cs, tests/Microsoft.Graph.Core.Test/Mocks/MockSerializer.cs, tests/Microsoft.Graph.Core.Test/Requests/BaseRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/MockSerializer.cs, tests/Microsoft.Graph.Test/Requests/Functional/OneDriveTests.cs, tests/Microsoft.Graph.Test/Requests/Functional/PlannerTests.cs
This allows them to get deserialized down the line, typically by the default `Serializer` class into `AdditionalData["responseHeaders"]` and `AdditionalData["statusCode"`.
[BaseRequest.cs](https://github.com/microsoftgraph/msgraph-sdk-dotnet/compare/response-headers?expand=1#diff-f0b9dd257bbefc270429de4a743d233b) - add headers to the response content. If the content stream is null, do not add headers, because the serializer is expecting a null object back. Because these will get picked up by the individual models later in the deserialization process, we need to temporarily re-serialize the headers and append them to the content stream to "trick" the serializer into deserializing them back into the object as additional data.
[MockSerializer](https://github.com/microsoftgraph/msgraph-sdk-dot …
=> Add response headers to the serialized response

src/Microsoft.Graph/Requests/Generated/AdministrativeUnitWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/DirectoryObjectWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/EducationClassWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/EducationSchoolWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/EducationUserWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/GroupWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/IAdministrativeUnitWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/IDirectoryObjectWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/IEducationClassWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/IEducationSchoolWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/IEducationUserWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/IGroupWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/IUserActivityWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/IUserWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/UserActivityWithReferenceRequest.cs, src/Microsoft.Graph/Requests/Generated/UserWithReferenceRequest.cs
Add the following methods to withReferenceRequest generated requests:
- CreateAsync (POST)
- UpdateAsync (PATCH)
- DeleteAsync (DELETE)
This allows you to create, update, and delete references to groups, document lists, etc. Not all methods may be applicable in all scenarios (refer to documentation on which workloads support which verbs).
=> With reference request delete method

src/Microsoft.Graph.Core/Exceptions/ErrorConstants.cs, src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs, src/Microsoft.Graph.Core/Requests/RedirectHandler.cs, src/Microsoft.Graph.Core/Requests/RetryHandler.cs, tests/Microsoft.Graph.Core.Test/Microsoft.Graph.Core.Test.csproj, tests/Microsoft.Graph.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.Core.Test/Requests/RedirectHandlerTests.cs, tests/Microsoft.Graph.Core.Test/Requests/RetryHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj, tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/MockRedirctHandler.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/RedirectHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/RetryHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Microsoft.Graph.DotnetCore.Test.csproj
Create GraphClientFactory class to offer client create instances of platform native HTTP client library that are pre-configured for making requests to Graph APIs
-Four CreateClient methods to create instances of HTTP client with different properties.
-CreatePipeline method to create middleware pipeline for the HTTP client
-Configure method to set default properties of the HTTP client
-Add non-param constructor methods to RetryHandler and RedirectHandler
-Requirements: https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/GraphClientFactory.md
-
-
=> Add GraphClientFactory class for middle ware 

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph/Microsoft.Graph.csproj, src/Microsoft.Graph/Requests/Extensions/TeamRequestExtensions.cs, tests/Microsoft.Graph.Test/Microsoft.Graph.Test.csproj, tests/Microsoft.Graph.Test/Requests/Functional/GroupTests.cs
Fixes #341 
Fixes #345
- Remove upper bounds on the Newtonsoft.Json package reference.
- Enable creation of a team on a group. 
`await graphClient.Groups[groupPage[8].Id].Team.Request().PutAsync(team);`
=> Update project Newtonsoft package reference and enable team creation on group

src/Microsoft.Graph.Core/Requests/AsyncMonitor.cs, src/Microsoft.Graph.Core/Requests/AuthenticationHandler.cs, src/Microsoft.Graph.Core/Requests/BaseClient.cs, src/Microsoft.Graph.Core/Requests/BaseRequest.cs, src/Microsoft.Graph.Core/Requests/HttpProvider.cs, src/Microsoft.Graph.Core/Requests/IBaseClient.cs, src/Microsoft.Graph.Core/Requests/IHttpProvider.cs, src/Microsoft.Graph.Core/Requests/RedirectHandler.cs, src/Microsoft.Graph/Requests/UploadChunkRequest.cs, tests/Microsoft.Graph.Core.Test/Mocks/MockAuthenticationProvider.cs, tests/Microsoft.Graph.Core.Test/Requests/AsyncMonitorTests.cs, tests/Microsoft.Graph.Core.Test/Requests/AuthenticationHandlerTests.cs, tests/Microsoft.Graph.Core.Test/Requests/BaseRequestTests.cs, tests/Microsoft.Graph.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.Core.Test/Requests/HttpProviderTests.cs, tests/Microsoft.Graph.Core.Test/Requests/RequestTestBase.cs, tests/Microsoft.Graph.Core.Test/TestModels/CustomRequest.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/AsyncMonitorTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/AuthenticationHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/CustomRequest.cs, tests/Microsoft.Graph.Test/Requests/Functional/ExcelTests.cs, tests/Microsoft.Graph.Test/Requests/Functional/MiscTests.cs, tests/Microsoft.Graph.Test/Requests/Functional/OneNoteTests.cs, tests/Microsoft.Graph.Test/Requests/Functional/ReportTests.cs, tests/Microsoft.Graph.Test/Requests/Functional/SharePointTests.cs
- **HttpProvider** uses **GraphClientFactory** to create a **HttpClient** that has **RedirectHandler**, **RetryHandler** & **AuthenticationHandler** delegating handlers.
- Updates **HttpProvider** to accept **AuthenticationProvider** in it's constructors because **AuthorizationHandler** depends on it.
- Removes setting of **cache control header, telemetry header & timeout** from **BaseRequest** & **HttpProvider** since it's handled by **GraphClientFactory**.
- Removes authentication of requests using **auhtenticationProvider** from **BaseRequest** since **AuthorizationHandler** handles this.
- Removes redirect handling from **HttpProvider** since **RedirectHandler** handles the same.
- Adds null check for response location header in **RedirectHandler** before issuing a redirect.
- Updates …
=> Http provider with graph client factory

src/Microsoft.Graph/Requests/Extensions/GraphServiceSitesCollectionRequestBuilderExtension.cs, src/Microsoft.Graph/Requests/Extensions/IGraphServiceSitesCollectionRequestBuilderExtension.cs, tests/Microsoft.Graph.Test/Requests/Functional/OneNoteTests.cs, tests/Microsoft.Graph.Test/Requests/Functional/SharePointTests.cs
Enables traversing a site's site hierarchy by using the root property. This allows a dev to find a site without needing to use GetByPath. This will make it easier to access a site's OneNote notebook.
@deepak2016 We will want to add the 'root' request builder property to enable this scenario for Java.
=> Fixes #374: Adds route to a Site's root structural property. 

src/Microsoft.Graph.Core/Extensions/RequestExtensions.cs, src/Microsoft.Graph.Core/Requests/AuthenticationHandler.cs, src/Microsoft.Graph.Core/Requests/RedirectHandler.cs, src/Microsoft.Graph.Core/Requests/RetryHandler.cs, tests/Microsoft.Graph.Core.Test/Requests/AuthenticationHandlerTests.cs, tests/Microsoft.Graph.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.Core.Test/Requests/RetryHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/AuthenticationHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/RetryHandlerTests.cs
C#'s HttpClient doesn't allow re-issuing of the same HttpRequestMessage as referenced [here](https://stackoverflow.com/questions/18000583/re-send-httprequestmessage-exception).
This PR adds the following changes to support the above:
- Adds an internal **CloneAsync** extension method to **HttpRequestMessage**.
- Updates the delegating handlers to use the CloneAsync method when performing a retry.
- Updates tests to consider the above changes.
=> Adds cloning of HttpRequestMessage before retry

src/Microsoft.Graph.Core/Requests/Middleware/AuthenticationHandler.cs, tests/Microsoft.Graph.Core.Test/Requests/Middleware/AuthenticationHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/AuthenticationHandlerTests.cs
- Updates AuthenticationHandlers SendRetryAsync to use per request authentication provider when one is set.
=> Updates AuthenticationHandlers SendRetryAsync to use per request provider.

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/BaseRequest.cs, src/Microsoft.Graph.Core/Requests/HttpProvider.cs, src/Microsoft.Graph.Core/Requests/Middleware/RedirectHandler.cs, tests/Microsoft.Graph.Core.Test/Microsoft.Graph.Core.Test.csproj, tests/Microsoft.Graph.Core.Test/Mocks/MockCustomHttpProvider.cs, tests/Microsoft.Graph.Core.Test/Requests/BaseRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/MockCustomHttpProvider.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs
This PR fixes the following issues reported in 1.14.0 release:
- Issue #413 - Slow concurrent requests when using our pipeline. This PR updates the middleware handlers order to always ensure `RedirectHandler` is the last handler in the pipeline. This significantly reduces the time it takes to process concurrent calls.
- Issue #417 - AuthorizationProvider is ignored when using a custom IHttpProvider. This PR ensures `AuthenticationProvider.AuthenticateRequestAsync` is always called in `BaseRequest` when using a custom `IHttpprovider`. It also adds a unit test for custom IHttpProvider.
=> Patches for V1.14.0

src/Microsoft.Graph.Core/Extensions/HttpRequestMessageExtensions.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Extensions/HttpRequestMessageExtensionsTests.cs
This PR is a fix for #435.
- Adds content request headers to cloned http request contents.
- Adds unit tests for CloneAsync.
=> Add request content headers to cloned http request.

src/Microsoft.Graph.Core/Requests/BaseRequest.cs, src/Microsoft.Graph.Core/Requests/ResponseHandler.cs, tests/Microsoft.Graph.Core.Test/Microsoft.Graph.Core.Test.csproj, tests/Microsoft.Graph.Core.Test/Requests/ResponseHandlerTests.cs
This PR allows using a native httpClient instance to get a HttpRequestMessage instance and then process it in a normal way to return a strongly typed object.
```csharp
var hrm = await httpClient.SendAsync(httpRequestMessage);
var user = await responseHandler.HandleResponse<User>(hrm);
```
=> Refactored response handling out of baseRequest

src/Microsoft.Graph.Core/Extensions/HttpClientExtensions.cs, src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs, src/Microsoft.Graph.Core/Requests/HttpProvider.cs, tests/Microsoft.Graph.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Extensions/HttpClientExtensionsTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneDriveTests.cs
This PR makes `GraphClientFactory` public.
- Add `AuthenticationHandler` to default handlers.
- Accept `IAuthenticationProvider` when creating default handlers and creating a new `HttpClient`.
- Make `GraphClientFactory` public.
- Update unit tests to reflect changes.
- Graph client factory [design doc](https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/GraphClientFactory.md).
=> Public Graph Client Factory

src/Microsoft.Graph.Core/Tasks/PageIterator.cs, src/Microsoft.Graph/Tasks/PageIterator.cs, tests/Microsoft.Graph.DotnetCore.Test/Mocks/MockUserEventsCollectionPage.cs, tests/Microsoft.Graph.DotnetCore.Test/Mocks/MockUserEventsCollectionRequest.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/GraphTestBase.cs, tests/Microsoft.Graph.DotnetCore.Test/Tasks/PageIteratorTests.cs
- Iterate and process the contents of a single page of a paged result set.
- Cancel and resume iteration.
- Store deltaLink in the iterator so that the iterator can be resumed at a indeterminate time in the future.
**Page results until a result item contains the word 'fire'**
```csharp
// Get an initial page results to populate the iterator.
IUserEventsCollectionPage iUserEventsCollectionPage = await graphClient.Me
.Events
.Request()
.Top(2)
.GetAsync();
// Create the callback to process each entity returned in the pages
Func<Event,bool> processEachEvent = (e) =>
{
bool shouldContinue = true;
if (e.Subject.Contains("fire"))
shouldContinue = false;
return shouldContinue;
}; 
// Create the iterator with the specified type
eventPageIterator = …
```
=> Page iterator

src/Microsoft.Graph.Core/Exceptions/ErrorConstants.cs, src/Microsoft.Graph.Core/Extensions/HttpClientExtensions.cs, src/Microsoft.Graph.Core/Extensions/HttpRequestMessageExtensions.cs, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/BaseRequest.cs, src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs, src/Microsoft.Graph.Core/Requests/HttpProvider.cs, src/Microsoft.Graph.Core/Requests/Middleware/AuthenticationHandler.cs, src/Microsoft.Graph.Core/Requests/Middleware/RedirectHandler.cs, src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs, tests/Microsoft.Graph.Core.Test/Extensions/BaseRequestExtensionsTests.cs, tests/Microsoft.Graph.Core.Test/Requests/BaseRequestTests.cs, tests/Microsoft.Graph.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.Core.Test/Requests/HttpProviderTests.cs, tests/Microsoft.Graph.Core.Test/Requests/Middleware/AuthenticationHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Extensions/BaseRequestExtensionsTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/TestHttpMessageHandler.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseClientTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/AuthenticationHandlerTests.cs
Fixes #
- Fixes #449. 
- Move static `HttpMessageHandler` and `Proxy` properties to `GraphClientFactory.Create` method as parameters.
- Fixes #447. 
- Override the default pipeline when a HttpMessageHandler is set on the HttpProvider.
- Remove null check on `AuthenticationHandler` since auth provider is optional when using `HttpProvider`.
- `BaseRequest` checks HttpClient for authHandler feature flag when using our `HttpProvider` before authenticating request.
- Add duplicate `httpMessageHandler` type check when creating a pipeline.
- Fixes #413.
- Drain HttpResponses if they have a response body before redirecting/retrying to avoid blocking subsequent requests.
- Fixes #435.
- Rewind content streams before reading stream content.
=> Client Factory Refactor

src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
Fixes #470 .
- Leave stream open after disposing `StreamWriter` object.
NOTE:
- This only affects NetCore 2.1 and above.
=> Keep stream open after disposing StreamWriter.

docs/overview.md
Was using delegate provider example to setup a new sample/mock provider for the [new XAML controls](https://aka.ms/wgt), but was having an auth problem.  Looks like the proxy expects a capital `B` which seems to be what I see in most examples.  Figured would be good to at least update the example for now until the proxy can be fixed to ignore case.
=> Bearer in Auth header needs to be capitalized (at least for proxy)

src/Microsoft.Graph/Requests/Extensions/DriveItemRequestBuilderExtensions.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Extensions/DriveItemRequestBuilderExtensionsTests.cs
Fixes #553
- Encode the path segment of the URI to ensure special characters are sorted out in accordance with the one drive expectations
- Adds tests to verify the URL
Therefore making a call in the code as follows should now **NOT** fail with an error.
```cs
var session = await client.Drives[DriveId].Root.ItemWithPath("Test#1.txt").CreateUploadSession().Request().PostAsync();
```
- https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/addressing-driveitems?view=odsp-graph-online
- https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/addressing-driveitems?view=odsp-graph-online#net--c-sharp--visual-basic
=> Fix for improper path encoding

src/Microsoft.Graph/Requests/Helpers/ChunkedUploadProvider.cs, src/Microsoft.Graph/Requests/Helpers/ReadOnlySubStream.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneDriveTests.cs
-  Avoid extra memory allocation when doing chunked upload
ChunkedUploadProvider trys to help with large file uploading, it divides the large stream to chunk-size stream and upload each one by one. The current implementation allocate maxChunksize of byte[] buffer each time:
```c#
var readBuffer = new byte[this.maxChunkSize]; // extra allocation
```
and an extra stream copy:
```c#
//extra copy 
await this.uploadStream.ReadAsync(readBuffer, 0, request.RangeLength).ConfigureAwait(false);
while (true)
{
using (var requestBodyStream = new MemoryStream(request.RangeLength))
{
await requestBodyStream.WriteAsync(readBuffer, 0, request.RangeLength).ConfigureAwait(false);
requestBodyStream.Seek(0, SeekOrigin.Begin);
...
}
}
```
If there is a total 500MiB size file, open a FileStream with a 10MiB …
=> Avoid extra memory allocation when doing chunked upload for large file

README.md
No code changes - simply updated the README to include link to the blog post illustrating the need for the recent version bump for easier discovery and to reflect the change to the project targets (e.g. .NET Standard 1.6 to 2.0 and .NET Framework 4.5 to 4.6.1).
I'd suggested making this change in a recent [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/631), but it occurred to me I could make the change and offer it up myself.
=> Updated readme to link post describing version bump, updated targets

scripts/IncrementMinorVersion.ps1
Reading the xml with correct encoding fixes the issue where script generates unwanted character in front of copyright.
Fixes #704
=> Fix powershell script to not introduce unwanted character in front of copyright

src/Microsoft.Graph/Exceptions/GeneratedErrorConstants.cs, src/Microsoft.Graph/Generated/model/AdministrativeUnit.cs, src/Microsoft.Graph/Generated/model/ScopedRoleMembership.cs, src/Microsoft.Graph/Generated/requests/ApplePushNotificationCertificateDownloadApplePushNotificationCertificateSigningRequestRequest.cs, src/Microsoft.Graph/Generated/requests/DeviceManagementVerifyWindowsEnrollmentAutoDiscoveryRequest.cs, src/Microsoft.Graph/Generated/requests/GroupLifecyclePolicyAddGroupRequest.cs, src/Microsoft.Graph/Generated/requests/GroupLifecyclePolicyRemoveGroupRequest.cs, src/Microsoft.Graph/Generated/requests/IDeviceManagementVerifyWindowsEnrollmentAutoDiscoveryRequest.cs, src/Microsoft.Graph/Generated/requests/IGroupLifecyclePolicyAddGroupRequest.cs, src/Microsoft.Graph/Generated/requests/IGroupLifecyclePolicyRemoveGroupRequest.cs, src/Microsoft.Graph/Generated/requests/IOrganizationSetMobileDeviceManagementAuthorityRequest.cs, src/Microsoft.Graph/Generated/requests/IUserRevokeSignInSessionsRequest.cs, src/Microsoft.Graph/Generated/requests/IWorkbookChartCountRequest.cs, src/Microsoft.Graph/Generated/requests/IWorkbookChartPointCountRequest.cs, src/Microsoft.Graph/Generated/requests/IWorkbookChartSeriesCountRequest.cs, src/Microsoft.Graph/Generated/requests/IWorkbookRangeBorderCountRequest.cs, src/Microsoft.Graph/Generated/requests/IWorkbookTableColumnCountRequest.cs, src/Microsoft.Graph/Generated/requests/IWorkbookTableCountRequest.cs, src/Microsoft.Graph/Generated/requests/IWorkbookTableRowCountRequest.cs, src/Microsoft.Graph/Generated/requests/OrganizationSetMobileDeviceManagementAuthorityRequest.cs, src/Microsoft.Graph/Generated/requests/UserRevokeSignInSessionsRequest.cs, src/Microsoft.Graph/Generated/requests/WorkbookChartCountRequest.cs, src/Microsoft.Graph/Generated/requests/WorkbookChartImageRequest.cs, src/Microsoft.Graph/Generated/requests/WorkbookChartPointCountRequest.cs, src/Microsoft.Graph/Generated/requests/WorkbookChartSeriesCountRequest.cs, src/Microsoft.Graph/Generated/requests/WorkbookRangeBorderCountRequest.cs, src/Microsoft.Graph/Generated/requests/WorkbookTableColumnCountRequest.cs, src/Microsoft.Graph/Generated/requests/WorkbookTableCountRequest.cs, src/Microsoft.Graph/Generated/requests/WorkbookTableRowCountRequest.cs, src/Microsoft.Graph/Microsoft.Graph.csproj
- fix method primitive return type
- expose GeneratedErrorConstants, thank you @bartlomiejzuber
=> Release 3.16

.editorconfig, Microsoft.Graph.sln, src/Microsoft.Graph/Microsoft.Graph.csproj, src/Microsoft.Graph/Tasks/PageIterator.cs, tests/Microsoft.Graph.DotnetCore.Test/Tasks/PageIteratorTests.cs
Fixes #852
- Add a delegate to PageIterator the allows consumers to configure the next page request ( `IBaseRequest` ) before it is invoked.
=> Add delegate to PageIterator to allow consumers to configure next page request

src/Microsoft.Graph/Microsoft.Graph.csproj
This PR is part of https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/219
This comes in as a new requirement as 4.6.1 is coming to EOL soon.
This PR updates the release notes in the csproj to capture recent updates to the branch
=> Update minimum netframework to v4.6.2 in feature/2.0

docs/tokencredentials.md, docs/upgrade-to-v4.md
This PR closes https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/256
It provides examples for users using the SDK examples for how to setup various TokenCredential instances to make the migration from Microsoft.Graph.Auth much faster and easier
=> Provide TokenCredential Samples in upgrade guide.

.azure-pipelines/ci-build.yml, scripts/GetNugetPackageVersion.ps1, src/Microsoft.Graph/Microsoft.Graph.csproj
This PR synchronizes the following PRs with the 2.0 branch to bring debug symbols support 
- #937 - Add source link to enable debugging of our NuGet package 
- #939 - Update nuget version script 
Artifacts produced for this PR/branch can be found [here](https://o365exchange.visualstudio.com/O365%20Sandbox/_build/results?buildId=5003652&view=results).
=> Debug Symbols support on feature/2.0

src/Microsoft.Graph/Generated/requests/GraphServiceClient.cs
This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/916.
It enables the users of the SDK to define their own base address for the requestbuilders in the event they are using their own httpclient and varying clouds.
=> Enable custom base address with httpclient constructor

src/Microsoft.Graph/Microsoft.Graph.csproj, src/Microsoft.Graph/Requests/Helpers/ChunkedUploadProvider.cs
These PR marks the ChunkedUploadProvider as obsolete so that intellisense can encourage SDK users to move to the LargeFileUploadTask.
Closes #980
=> Mark ChunkedUploadProvider as obsolete

docs/tokencredentials.md, docs/upgrade-to-v4.md, src/Microsoft.Graph/Generated/requests/GraphServiceClient.cs
This PR makes the properties of GraphServiceClient virtual to enable the use of mocking frameworks such as Moq to be able to override the implementations provided in the class after the dropping of the IGraphServiceClient interface.
Sdk users should now be able to initialize an mock of the GraphServiceClient for testing by doing something similar to the code below.
**Example**
```cs
// create mocks
var mockAuthProvider = new Mock<IAuthenticationProvider>();
var mockHttpProvider = new Mock<IHttpProvider>();
var mockGraphClient = new Mock<GraphServiceClient>(mockAuthProvider.Object, mockHttpProvider.Object);
ManagedDevice md = new ManagedDevice
{
Id = "1",
DeviceCategory = new DeviceCategory()
{
Description = "Sample Description"
}
};
// setup the calls
mockGraphClient.Setup(g => …
```
=> Make properties of GraphServiceClient virtual (v1)

src/Microsoft.Graph/Requests/Helpers/ChunkedUploadProvider.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/MailTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/ActionRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/CollectionReferencesRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/CollectionWithReferencesRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/EntityCollectionRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/EntityReferenceRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/EntityRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/EntityWithReferenceRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/FunctionRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/MediaEntityStreamRequestTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/ThumbnailRequestTests.cs
Fixes https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/704
The root cause is that there is an upcoming type in beta metadata that collides with System.Threading.Tasks.Task. Disambiguated those names in this PR.
The upcoming type:
```xml
<EntityType Name="task" BaseType="graph.baseTask"/>
```
Staging pipeline for beta is also using this repo, so fix initially goes in here. But I will apply the same fix in msgraph-beta-sdk-dotnet repo as well:
----
https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=61504&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=006e6f7c-8314-5e02-a3df-483f3a1f4cfa&l=5859
https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=61583&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7 …
=> Disambiguate Task

README.md
This PR fixes the incorrect minimum version for the v4 SDK in the readme in .Net Framework from 4.6.1 to 4.6.2 as outlined in the upgrade guide
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1275
=> Update README.md to reflect correct .NET framework version

src/Microsoft.Graph/Microsoft.Graph.csproj
This is part of https://github.com/microsoft/kiota-abstractions-dotnet/issues/12
It changes the target runtime to netstandard2.0
=> Change target runtime to netstandard 2.0

CONTRIBUTING.md, README.md, docs/collections.md, docs/headers.md, docs/overview.md, docs/readme.md, docs/upgrade-to-v5.md
This PR closes #1335 
It updates the samples in the upgrade guide to reflect changes to the request configuration after changes made in https://github.com/microsoft/kiota/pull/1520
=> Refactor code samples after request configuration revamp

CHANGELOG.md, docs/upgrade-to-v5.md, src/Microsoft.Graph/GraphServiceClient.cs, src/Microsoft.Graph/Microsoft.Graph.csproj
This PR
- Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1609 to omit v1 in the telemetry header
- Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1601 to create easier passing of `IAuthenticationProvider` when using the httpClient
- Updates the updated guide to capture renaming `CreateXXXRequestInformation` methods to `ToXXXRequestInformation`
- Update changelog and project for rc.2 release
=> Upgade guide update and release

docs/upgrade-to-v5.md
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1705
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1709
Includes information on how to pass per-request options like the RetryHandlerOptions to requests in the SDK.
=> Include per-request options in upgrade guide.

README.md, src/Microsoft.Graph/Extensions/CustomBatchRequestBuilder.cs, src/Microsoft.Graph/GraphServiceClient.cs
This PR depends on https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/637
Adds a derived BatchRequestBuilder to allow passing for errormappings to allow for consistent errors. and closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1782
Also closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1784
=> Adds derived BatchRequestBuilder

.github/policies/msgraph-sdk-dotnet-branch-protection.yml
Initial commit [generated from the existing UI set branch policies using GH CLI](https://github.com/MIchaelMainer/policyservicetoolkit/blob/main/branch_protection_export.ps1). 
Carefully review the policy for additions and changes that should be added here. Review subsequent commits for changes to policy. 
> IMPORTANT: Policy changes can be disruptive to workflows.
=> - add branch protection policy file

docs/errors.md
Convert HttpStatusCode.NotFound to INT before comparing with odataError.ResponseStatusCode
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2085
- Convert HttpStatusCode.NotFound to INT before comparing with odataError.ResponseStatusCode
=> Update errors.md to fix code example issue

README.md
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2233
Changes internal links in readme to absolute URLs to ensure the readme in the nuget listing has valid links.
=> Use absolute urls in readme

docs/upgrade-to-v5.md
Fixes #1884 
- Updates the breaking change documentation of the SDK V5. It is the version that introduces the use of  the standard OData query parameters(`$search`, `$select`). These are behaving differently than the query parameters in the previous versions. However this change of behaviour is not documented in this repo or the official MS docs documentation.
- This PR aims to warn the users of the above issue and give some advice on what they can do avoid being blocked by it.
- [MS Docs documentation on how to search for a site](https://learn.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http)
- The provided example does not work in the V5 SDK. Neither is the HTTP example showing how to do queries with `$search`
=> Update upgrade-to-v5.md to include difference between non-OData and OData query parameter values

.azure-pipelines/ci-build.yml, guardian/SDL/.gdnbaselines, guardian/SDL/.gdnsuppress, scripts/GetNugetPackageVersion.ps1, scripts/ValidateUpdatedNugetVersion.ps1, src/Microsoft.Graph/Microsoft.Graph.csproj
Part of https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/808
Changes include
- Move deployment to yaml configuration to deprecate old release management
- Use 1es compliant templates
Notes.
- Binskim is consistently crashing with the error `System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.` on the build. This has been disabled with the justification as documented at [here](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/disablingtools#s360-exception-process-and-approvals-for-disabled-tools)
=> [Compliance] Pipeline compliance

docs/tokencredentials.md
There Overview samples are V5 compliant, however, the Credential samples are V4 base, considering V5 is the latest, I presume users could prefer to see the latest samples, only look back into the v4 samples in the upgrade snippet.
This is a better idea as opposed to work with V4 snippets and look out how it works for V5 which is the latest.
=> Update samples to be V5 compliant

.github/dependabot.yml
=> fix: use directories for dependabot configuration

src/Microsoft.Graph/GraphServiceClient.cs, tests/Microsoft.Graph.DotnetCore.Test/Models/ModelSerializationTests.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneNoteTests.cs
Follow up to https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/879
Cleans up obsolete methods in tests.
=> fix: update to use non obsolete constructors and methods

.azure-pipelines/ci-build.yml
Fixes double tagging and double releases from CI and release please
=> ci: fixing double tagging and GH releases

src/Microsoft.Graph/Extensions/UploadSession.cs, tests/Microsoft.Graph.DotnetCore.Test/Models/Extensions/UploadSessionTests.cs
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/903 to resolve trimming warnings due to reflection used.
Depends on merge of https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2649
=> fix: updated the UploadSession model to implement IUploadSession

README.md
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2654
=> docs: fixes broken links in Readme

.azure-pipelines/ci-build.yml
Current settings only will deploy on runs from main.
=> ci: set deployment to occur either manually or tagged commit
