microsoftgraph/msgraph-sdk-dotnet

README.md, docs/overview.md
Fixes issue
"2 links to "overview" in readme.md are incorrect #2"
=> Fix incorrect docs/overview links

README.md
=> Fixing hyperlink to sample

src/Microsoft.Graph.Core/Requests/BaseRequest.cs, src/Microsoft.Graph.Core/Requests/IHttpProvider.cs, tests/Microsoft.Graph.Core.Test/Requests/BaseRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/ActionRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/CollectionReferencesRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/CollectionWithReferencesRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/EntityCollectionRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/EntityReferenceRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/EntityRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/EntityWithReferenceRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/FunctionRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/MediaEntityStreamRequestTests.cs, tests/Microsoft.Graph.Test/Requests/Generated/ThumbnailRequestTests.cs
=> Pipe through cancellation token and completion options on BaseRequest.SendAsync

docs/collections.md
IGraphServiceGroupsCollectionPage.AdditionData is actually .Addition**al**Data.
=> Fixed wrong property name.

src/Microsoft.Graph.Core/Exceptions/ServiceException.cs, src/Microsoft.Graph.Core/Requests/HttpProvider.cs, tests/Microsoft.Graph.Test/Requests/Functional/MailTests.cs
Reverts microsoftgraph/msgraph-sdk-dotnet#80
Getting master branch to match the currently published NuGet package. Will reintegrate later.
=> Revert "Provided pass through of response headers and status code for excepti…"

src/Microsoft.Graph.Core/Exceptions/ServiceException.cs, src/Microsoft.Graph/Helpers/EtagHelper.cs, src/Microsoft.Graph/Models/Helpers/ComplexTypeHelper.cs, src/Microsoft.Graph/Models/Partials/PlannerAppliedCategories.cs, src/Microsoft.Graph/Models/Partials/PlannerAssignedToTaskBoardTaskFormat.cs, src/Microsoft.Graph/Models/Partials/PlannerAssignment.cs, src/Microsoft.Graph/Models/Partials/PlannerAssignments.cs, src/Microsoft.Graph/Models/Partials/PlannerChecklistItem.cs, src/Microsoft.Graph/Models/Partials/PlannerChecklistItems.cs, src/Microsoft.Graph/Models/Partials/PlannerExternalReference.cs, src/Microsoft.Graph/Models/Partials/PlannerExternalReferences.cs, src/Microsoft.Graph/Models/Partials/PlannerOrderHintsByAssignee.cs, src/Microsoft.Graph/Models/Partials/PlannerUserIds.cs, src/Microsoft.Graph/Requests/Helpers/EtagHelper.cs, src/Microsoft.Graph/Requests/Helpers/HeaderHelper.cs, tests/Microsoft.Graph.Test/Requests/Functional/EventTests.cs, tests/Microsoft.Graph.Test/Requests/Functional/PlannerTests.cs
Adding Planner related partial implementations.
Adding helpers for dealing complex values properties in open types.
Adding helpers for etag handling and general header management.
Update service exception to be informative by default.
Adding planner tests for more complex scenarios.
=> Planner focus

tests/Microsoft.Graph.Test/Requests/Functional/ExcelTests.cs
Some Excel OData function endpoints do not accept fully qualified function names when the should. Test case is for a workaround in this scenario.
=> Workaround for functions with FQN

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph/Microsoft.Graph.csproj
This will be added to nuget package with dotnet pack. There are some bad comments that will need to be cleaned up in our templates. Next step will be to add comments from the docs.
=> Added configuration so that we generate intellisense

docs/overview.md
Only two grammatical corrections have been made in the overview.md file.
=> Perform small grammatical corrections

src/Microsoft.Graph/Requests/Extensions/ISiteRequestBuilderExtensions.cs, src/Microsoft.Graph/Requests/Extensions/SiteRequestBuilderExtensions.cs
- Add SiteWithPath using ItemWithPath as a template
=> Add SiteWithPath

tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
- Update MOQ reference from 4.7.1 to 4.8.1. This should fix issues related to https://github.com/moq/moq4/issues/375.
=> VS 2017 - Updated Moq reference for MS Graph

README.md
- Add instructions on how to build the library locally for users looking to contribute to the code base
=> Add notes on building the library

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Properties/AssemblyInfo.cs, src/Microsoft.Graph/Enums/ClientType.cs, src/Microsoft.Graph/Microsoft.Graph.csproj
Update release versions and release notes
=> Release updates

src/Microsoft.Graph/Requests/Extensions/GraphServiceSitesCollectionRequestBuilderExtension.cs, tests/Microsoft.Graph.Test/Requests/Functional/SharePointTests.cs
=> Get by path helper

docs/overview.md
=> Fixed typo and broken link

tests/Microsoft.Graph.Test/Microsoft.Graph.Test.csproj, tests/Microsoft.Graph.Test/packages.config
Fixes #
- Updating MSAL library to 1.1.2-preview
-
-
-
-
-
=> Update MSAL to 1.1.2-preview

src/Microsoft.Graph/Microsoft.Graph.csproj, src/Microsoft.Graph/Properties/AssemblyInfo.cs
- Update System.Net.Http to address security issue.
=> Updated System.Net.Http from 4.3.1 to 4.3.3

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Properties/AssemblyInfo.cs, src/Microsoft.Graph/Microsoft.Graph.csproj, src/Microsoft.Graph/Properties/AssemblyInfo.cs
* Bumped version.
* Added release notes.
=> July update

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Properties/AssemblyInfo.cs, src/Microsoft.Graph/Microsoft.Graph.csproj, src/Microsoft.Graph/Properties/AssemblyInfo.cs
This PR depends on #298 . Only pull this after 298.
=> Updated copyright, version, and release notes.

src/Microsoft.Graph.Core/Exceptions/ErrorConstants.cs, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/RetryHandler.cs, src/Microsoft.Graph/Microsoft.Graph.csproj, tests/Microsoft.Graph.Core.Test/Microsoft.Graph.Core.Test.csproj, tests/Microsoft.Graph.Core.Test/Requests/RedirectHandlerTests.cs, tests/Microsoft.Graph.Core.Test/Requests/RetryHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/RetryHandlerTests.cs, tests/Microsoft.Graph.Test/Microsoft.Graph.Test.csproj
-Add RetryHandler Class in middleware to deal with retry process for status code 429/503
-Implements Delegating Handler and override SendAsync Method
-Create SendRetryAsync method for retry process
-Add several help methods
-Microsoft Graph Design: https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RetryHandler.md
-References: https://github.com/Microsoft/api-guidelines/pull/72
=> Add retry handler

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Properties/AssemblyInfo.cs, src/Microsoft.Graph/Microsoft.Graph.csproj, src/Microsoft.Graph/Properties/AssemblyInfo.cs
This PR needs to be pull before #331
=> Updated nuspec release notes, bumped version.

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph/Microsoft.Graph.csproj, tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/MockRedirctHandler.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
- Makes GraphClientFactory internal
- Updates HttpProvider to use GraphClientFactory
- Fixes broken GraphClientFactory test
=> January Release

src/Microsoft.Graph/Microsoft.Graph.csproj
=> Updated minor version and cleared the release notes.

src/Microsoft.Graph.Core/LICENSE.txt, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Properties/AssemblyInfo.cs
This PR adds 1.15.0 preview.1 release notes and package version in .csproj.
=> 1.15.0 preview 1 release notes

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph/Microsoft.Graph.csproj, src/Microsoft.Graph/Properties/AssemblyInfo.cs
* Update M.G.C version to 1.15.0
* Accumulated preview release notes.
* Updated M.G.csproj to define the assemblyinfo.
=> Final update for Build

src/Microsoft.Graph/Models/Extensions/TeamsTabExtension.cs
=> Added the OdataBind property

src/Microsoft.Graph/Models/Extensions/UploadSession.cs
This PR updates UploadSession to implement IUploadSession to provide request builder compatibility with the LargeFileUploadTask work on this [PR](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/65).
This should be merged in after the PR has been completed and deployed.
=> Update UploadSession to implement IUploadSession

.azure-pipelines/generate-v1.0-sdk.yml, scripts/IncrementMinorVersion.ps1
Same as https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/89
> Note: Peter and I propose that azure pipeline definitions be put in a dir named .azure-pipelines like what they do in Azure SDK
=> Pipeline for generating service library

.azure-pipelines/generate-v1.0-sdk.yml
Adds a `[skip ci]` tag into commit message if the pipeline run is manual.
=> adds [skip ci] for manual pipeline runs

README.md
as per https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/721#issuecomment-665809861
=> Readme.md: Add 'Upgrading from v1' section

README.md, docs/upgrade-to-v4.md
This PR submits an upgrade guide for the sdk users who will potentially upgrade to the next version of the .Net sdks.
It outlines the changes in place and what users should be aware of during the upgrade process.
=> Upgrade guide for v4 changes.

.azure-pipelines/ci-build.yml, src/Microsoft.Graph/Microsoft.Graph.csproj
Fixes #747 
Related to https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/247
=> Add source link to enable debugging of our NuGet package

docs/overview.md
This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/767
=> Close issue 767

src/Microsoft.Graph/Microsoft.Graph.csproj
=> Bump version to 3.30

docs/upgrade-to-v4.md
Fix example code with correct variable name
=> Fix example code with correct variable name

docs/upgrade-to-v4.md
- Note in upgrade-to-v4 doc on suggesting Microsoft.Identity.Web library for Web/API scenarios.
- Twitter thread: https://twitter.com/baywet/status/1393073053026955266
=> Note added about using Microsoft Identity Web in Web/API scenarios

docs/tokencredentials.md
=> - adds device code callback to token credentials guide

src/Microsoft.Graph/Generated/model/Application.cs, src/Microsoft.Graph/Generated/model/ChatMessage.cs, src/Microsoft.Graph/Generated/model/ServicePrincipal.cs, src/Microsoft.Graph/Generated/model/WorkforceIntegration.cs, src/Microsoft.Graph/Microsoft.Graph.csproj
=> Release 3.34.0

src/Microsoft.Graph/Microsoft.Graph.csproj, src/Microsoft.Graph/Models/Extensions/ChangeNotification.cs, src/Microsoft.Graph/Models/Extensions/ChangeNotificationCollection.cs, src/Microsoft.Graph/Models/Extensions/ChangeNotificationEncryptedContent.cs, src/Microsoft.Graph/Models/Extensions/Subscription.cs
This PR is part of https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/268.
It complements the work in https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/269 and should build once its merged in.
=> Rich notifications support

docs/upgrade-to-v4.md
This PR updates the upgrade guide to include information about
- Rich notifications support
- Setting of the @odata.type property in generated types
=> Updates to the upgrade guide

docs/upgrade-to-v4.md
Separating the upgrade guide into sections:
- Breaking changes
- New capabilities
- Bug fixes
=> Update the upgrade-to-v4

docs/upgrade-to-v4.md
As we agreed, here is a small addendum to make it clear that we need to use the "isolated process" model for .NET 5.0, when creating Azure Functions with Microsoft Graph .NET SDK v4. Thanks.
=> Added bullet about Azure Functions isolated process for .NET 5.0

docs/upgrade-to-v4.md
This PR closes #1236 
It covers missing guidance with relation to effects of work done to encode url when building SDK requests covered in V4 upgrade.
=> Update v4 upgrade guide to cover URL encoding

.github/workflows/validatePullRequest.yml, Nuget.Config, README.md, docs/collections.md, docs/headers.md, docs/overview.md, docs/upgrade-to-v5.md, src/Microsoft.Graph/GraphServiceClient.cs, src/Microsoft.Graph/Microsoft.Graph.csproj
This PR creates updates for the preview release
Changes include: 
- Introduced `GraphServiceClient` to tie to graph core
- Adds upgrade guide to cover changes from V4
- Updates docs with updates code samples
- Update CI to use public sources.
=> Kiota preview updates

docs/upgrade-to-v5.md
following the rename in kiota generation
=> - updates the named parameters names

docs/upgrade-to-v5.md
Closes #1368 
This PR updates the upgrade guide with guidance on Auth scenarios.
=> Upgrade guide updates

docs/overview.md
Fixes dead lines in overview.md
- Replacing dead links with appropriate live links
=> Update dead links in overview docs

docs/upgrade-to-v5.md
Adds example with multiple params to the upgrade guide to address https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1290#issuecomment-1273801763
=> Adds example with multiple parameters to upgrade guide

docs/upgrade-to-v5.md
This PR makes a couple of updates to the upgrade guide to cover
- Using of alternate paths when accessing drive paths.
- Namespace/Using changes for type locations on migration.
=> Upgrade guide improvements

.github/CODEOWNERS
=> Cleanup code owners

CHANGELOG.md, src/Microsoft.Graph/Microsoft.Graph.csproj
=> Release 5.0.0

src/Microsoft.Graph/Enums/GraphErrorCode.cs
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/608
- Added missing error code to `GraphErrorCode.cs` in alphabetical order.
=> Added ImageNotFound error code

docs/upgrade-to-v5.md
Follows up @olivermue comments in #1715
=> Follow up to 1715

docs/upgrade-to-v5.md
this addresses the suggestion to add an example of handling failing responses 429er https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1759
Fixes #1759 
- adding example to the md file according to the issue discussion.
=> adding failing response example in batch

docs/upgrade-to-v5.md
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/636
Related to #1759
@andrueastman here you go
=> docs: Information on batching

src/Microsoft.Graph/Enums/GraphErrorCode.cs
Fixes #1793
- Add **Request_ResourceNotFound** error code thrown by Graph
=> Add Request_ResourceNotFound error code

docs/upgrade-to-v5.md
Updates guide with guidance on how to fetch the root drive
Related https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1848
Related https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1876
=> Updates guide for /drive/root paths

.azure-pipelines/ci-build.yml, src/Microsoft.Graph/Microsoft.Graph.csproj
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1430
Related to https://github.com/microsoft/kiota/issues/2757
=> Fixes package icon/Readme  and credscan version

README.md
Fixes #
- Updated README.md with info how to handle long paths on Windows
-
-
-
-
-
=> Added info how to enable long paths for Windows OS

docs/upgrade-to-v5.md
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1689
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2014
Updates guide on entire url being opaque and usage examples of how to use the url.
=> Update guide on delta query parameters.

docs/errors.md
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2069
=> Update errors.md to do case insensitive comparison

README.md
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2184
=> Update README.md to capture missing drive path

src/Microsoft.Graph/Extensions/DriveItemRequestBuilderExtensions.cs, tests/Microsoft.Graph.DotnetCore.Test/Requests/Extensions/DriveItemRequestBuilderExtensionsTests.cs
Fixes #2252 
- Added missing members to `CustomDriveItemItemRequestBuilder`
- Added unit tests to `DriveItemRequestBuilderExtensionsTests`
=> Extend CustomDriveItemItemRequestBuilder

.github/workflows/project-auto-add.yml
Relates to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2428
- the status workflow will be added in the workflow [here](https://github.com/orgs/microsoftgraph/projects/55/workflows)
=> chore: Add github action to add new PR or issue to Project

src/Microsoft.Graph/Microsoft.Graph.csproj
=> Not able to build SDK on local

.github/workflows/project-auto-add.yml
=> chore!: replaces project bot token task by official one

docs/overview.md
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2555
=> Update broken link

.azure-pipelines/ci-build.yml
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2612
Todo
=> ci: upgrades esrp sign tasks

.azure-pipelines/ci-build.yml, .github/policies/msgraph-sdk-dotnet-branch-protection.yml, .github/release-please.yml, .github/workflows/validatePullRequest.yml, CONTRIBUTING.md, README.md, docs/contributions.md, scripts/GetLatestCommitSHA.ps1, src/Microsoft.Graph/Microsoft.Graph.csproj
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2595
Todo
=> chore: align branch to single main branch

.azure-pipelines/ci-build.yml, .github/policies/msgraph-sdk-dotnet-branch-protection.yml, .github/release-please.yml, .github/workflows/validatePullRequest.yml, CONTRIBUTING.md, README.md, docs/contributions.md, release-please-config.json, scripts/GetLatestCommitSHA.ps1, src/Microsoft.Graph/Microsoft.Graph.csproj
Syncs dev with master before rename to main
=> Merge dev to master

README.md
Dummy commit to validate CI processes and release please after branch rename
=> docs: fix links in readme to upgrade guide

guardian/SDL/.gdnbaselines, guardian/SDL/.gdnsuppress
Updates baselines dues to false positives in dom export file
=> chore: update baselines due to false positives in kiota-export file

.azure-pipelines/ci-build.yml
new security requirements https://aka.ms/1espt/custom-release-job, context https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=171557&view=logs&j=4cdea4ed-d555-50bf-6c7b-6f3e8cd00008&t=c1787207-6a3b-514d-aca5-6c646859a715&l=12
=> security: adds required pipeline metadata

.azure-pipelines/ci-build.yml
=> ci: fixes assets upload to GH release

src/Microsoft.Graph/Extensions/DriveItemRequestBuilderExtensions.cs
Fixes #2909 
- Fixed reference on VersionsRequestBuilder
- https://stackoverflow.com/questions/79625806/using-ms-graph-api-to-get-version-list-and-version-with-minimal-api-requests
=> Fixed reference on VersionsRequestBuilder

.github/workflows/release-please.yml
=> chore: add release-please GHA
